[package]
name = "estella"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
num-traits = "0.2.14"
serde = { version = "1.0.136", features = ["derive"] }
serde_yaml = "0.8.23"
serenity = "0.10.10"
sha3 = "0.10.0"
tokio = { version = "1.16.1", features = ["full"] }
